### ISSUE TITLE
[HELP][NOT-X510] com.android.phone crashes

### ISSUE THREAD

**Issue by aymende7** [Rendyindo/Flyme_X510-cm#4]
i used cm as base 
bootloop after flashing fullota
here is the log 

--------- beginning of crash
01-01 14:09:21.196 728 2392 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.ui
01-01 14:09:21.196 728 2392 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle android.content.IContentProvider.call(java.lang.String, java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference
01-01 14:09:21.196 728 2392 E AndroidRuntime: at cyanogenmod.providers.CMSettings$NameValueCache.getStringForUser(CMSettings.java:242)
01-01 14:09:21.196 728 2392 E AndroidRuntime: at cyanogenmod.providers.CMSettings$System.getStringForUser(CMSettings.java:516)
01-01 14:09:21.196 728 2392 E AndroidRuntime: at cyanogenmod.providers.CMSettings$System.getIntForUser(CMSettings.java:561)
01-01 14:09:21.196 728 2392 E AndroidRuntime: at com.android.server.policy.PhoneWindowManager.updateKeyAssignments(PhoneWindowManager.java:1876)
01-01 14:09:21.196 728 2392 E AndroidRuntime: at com.android.server.policy.PhoneWindowManager.init(PhoneWindowManager.java:1713)
01-01 14:09:21.196 728 2392 E AndroidRuntime: at com.android.server.wm.WindowManagerService$4.run(WindowManagerService.java:906)
01-01 14:09:21.196 728 2392 E AndroidRuntime: at android.os.Handler$BlockingRunnable.run(Handler.java:759)
01-01 14:09:21.196 728 2392 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:739)
01-01 14:09:21.196 728 2392 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:95)
01-01 14:09:21.196 728 2392 E AndroidRuntime: at android.os.Looper.loop(Looper.java:148)
01-01 14:09:21.196 728 2392 E AndroidRuntime: at android.os.HandlerThread.run(HandlerThread.java:61)
01-01 14:09:21.196 728 2392 E AndroidRuntime: at com.android.server.ServiceThread.run(ServiceThread.java:46)
 
thanks in advance

**Comment by rorre** [comment]
Please post full log.

**Comment by aymende7** [comment]
[logcat](https://github.com/FlymeOS/manifest/files/1131755/logcat.txt)
[errors only.txt](https://github.com/Rendyindo/Flyme_X510-cm/files/1135304/errors.only.txt)

**Comment by rorre** [comment]
https://github.com/Rendyindo/Flyme_X510-cm/blob/marshmallow-6.0/Makefile#L57

Take a look at the variable, and match it with yours.

**Comment by aymende7** [comment]
TeleService added 
should i remove BluetoothExt
[Makefile.zip](https://github.com/Rendyindo/Flyme_X510-cm/files/1135325/Makefile.zip)
thanks a lot

**Comment by rorre** [comment]
No dont add TeleService.
Probaly just test with adding CMSettingsProvider

**Comment by aymende7** [comment]
solved but still stuck in bootloop
[logcat.txt](https://github.com/Rendyindo/Flyme_X510-cm/files/1135493/logcat.txt)
thanks

**Comment by rorre** [comment]
```
01-03 08:36:31.945  3749  3751 I dex2oat : Verification error in void gnu.crypto.hash.Haval.transform(byte[], int)
01-03 08:36:31.945  3749  3751 I dex2oat : void gnu.crypto.hash.Haval.transform(byte[], int) failed to verify: void gnu.crypto.hash.Haval.transform(byte[], int): [0xB] Invalid reg type for array index (Precise Reference: byte[])
01-03 08:36:31.946  3749  3751 W dex2oat : Verification failed on class gnu.crypto.hash.Haval in FileManager.apk because: Verifier rejected class gnu.crypto.hash.Haval due to bad method void gnu.crypto.hash.Haval.transform(byte[], int)
01-03 08:36:35.831  3749  3750 W dex2oat : No verified method for method calling String.<init>: java.lang.String java.io.ByteArrayOutputStream.toString()
01-03 08:36:37.481  3749  3749 I dex2oat : Skipping compilation of byte[] gnu.crypto.util.Util.toReversedBytesFromString(java.lang.String): it contains a non natural loop
```

the log is still incomplete, please send tombstones too (avaible at /data/tombstones)

**Comment by aymende7** [comment]
[tombstones.zip](https://github.com/Rendyindo/Flyme_X510-cm/files/1135527/tombstones.zip)

**Comment by rorre** [comment]
uh-oh! looks like libandroid_runtime.so is not working.
Try to use vendor libandroid_runtime.so.

**Comment by aymende7** [comment]
from vendor folder?

**Comment by rorre** [comment]
yeah, take it from /system/lib/ of the CM13 rom.

**Comment by aymende7** [comment]
[tombstones.zip](https://github.com/Rendyindo/Flyme_X510-cm/files/1135590/tombstones.zip)
same problem ;-;
got this problem with miui patchrom too

**Comment by rorre** [comment]
try to ask in FlymeOS/manifest issues, sorry, but I cant help you more becouse I haven't experienced this.

**Comment by aymende7** [comment]
ok thanks a lot.

**Comment by aymende7** [comment]
how to fix this ?
thank you
out/obj/system/framework/services.WjA/smali/com/android/server/SystemServer.smali[3197,4] There is already a label with that name.
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: com/android/server/SystemServer.smali
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:75)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:59)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:404)
	at brut.androlib.Androlib.buildSources(Androlib.java:335)
	at brut.androlib.Androlib.build(Androlib.java:291)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
/mnt/WorkSpace/flyme/build/main.mk:451: recipe for target 'out/obj/system/framework/services.jar' failed
make[1]: *** [out/obj/system/framework/services.jar] Error 161
make[1]: Leaving directory '/mnt/WorkSpace/flyme/devices/aokp_piccolo'
/mnt/WorkSpace/flyme/build/main.mk:34: recipe for target 'ota' failed
make: *** [ota] Error 2

<<< fullota failed

**Comment by sostk** [comment]
(RendyAK) Log mirrored: https://transfer.sh/f4IPT/log.txt


help me wit this please

**Comment by rorre** [comment]
@aymende7 check services.jar.out/smali/com/android/server/SystemServer.smali line 3197, make sure you don't have the double label (like `:try_start_0`) in a file.

@sostk Check
https://github.com/FlymeOS/devices-base_cm/tree/marshmallow-6.0/SystemUI/smali/com/android/systemui/keyguard
https://github.com/FlymeOS/devices-base_cm/tree/marshmallow-6.0/TeleService/smali/com/android/phone
https://github.com/FlymeOS/devices-base_cm/tree/marshmallow-6.0/Telecom/smali/com/android/server/telecom
these folders, I guess.

**Comment by sostk** [comment]
@Rendyindo  please can you help me???

**Comment by rorre** [comment]
@sostk also https://github.com/FlymeOS/devices-base_cm/blob/marshmallow-6.0/Makefile#L110

**Comment by sostk** [comment]
I have that all. as you said

**Comment by rorre** [comment]
ok, dont take tombstones, try to take a logcat, and upload it somewhere, **dont copy paste it here**.

**Comment by sostk** [comment]
[flyme6_2.txt](https://github.com/Rendyindo/Flyme_X510-cm/files/1182721/flyme6_2.txt)

**Comment by sostk** [comment]
here is the logcat

**Comment by sostk** [comment]
there are 4 :try_start_0 in systemserver.smali

**Comment by aymende7** [comment]
[SystemServer.smali.zip](https://github.com/Rendyindo/Flyme_X510-cm/files/1182722/SystemServer.smali.zip)
`:try_start_3b`

**Comment by rorre** [comment]
I'll check out stuffs this night

**Comment by aymende7** [comment]
help :/

**Comment by rorre** [comment]
@aymende7 can you give me the SystemServer.smali reject file?
sorry for being late

**Comment by sostk** [comment]
I do not get any systemserver.smali reject .

**Comment by rorre** [comment]
I don't mean to you @sostk , I mean to @aymende7 .
Also @sostk to prevent confusion, can you create another issue here?

**Comment by sostk** [comment]
Ok no worries.

**Comment by aymende7** [comment]
@Rendyindo https://github.com/Rendyindo/Flyme_X510-cm/files/1184871/SystemServer.smali.zip

**Comment by rorre** [comment]
@aymende7 there, there's probaly a double `:try_start_3b` and you seems to apply the reject wrong.

**Comment by aymende7** [comment]
ok i will try again thanks

**Comment by aymende7** [comment]
\(^o^)/YES ！ booted thanks a lot 
![s00105-165133](https://user-images.githubusercontent.com/25817880/28750389-1263280a-74e1-11e7-8c12-08a48333a070.jpg)
one problem com.andriod.phone FC

**Comment by sostk** [comment]
@aymende7  which device>??

**Comment by rorre** [comment]
@aymende7 nice, if you're using mediatek device, add https://github.com/Rendyindo/Flyme_X510-cm/tree/marshmallow-6.0/TeleService/smali/com/mediatek/phone and https://github.com/Rendyindo/Flyme_X510-cm/blob/marshmallow-6.0/Makefile#L111

**Comment by aymende7** [comment]
soory i am using bq m5 （qualcomm snapdragon 615）

**Comment by rorre** [comment]
Oh ok, as always, capture logcat.

**Comment by aymende7** [comment]
ok i will flash it again

**Comment by aymende7** [comment]
https://hastebin.com/ponucofoya.cs

**Comment by aymende7** [comment]
https://github.com/coderstory/flyme6_device_gemini/commit/8988aba6e0f277ffd9267f8feeb9c261b69e4359
i'll try this

**Comment by rorre** [comment]
Full log plz

**Comment by aymende7** [comment]
[logcat.txt](https://github.com/Rendyindo/Flyme_X510-cm/files/1185614/logcat.txt)

**Comment by aymende7** [comment]
same problem :(

**Comment by aymende7** [comment]
nvrm solved by adding telresource to vendor saved apps

**Comment by aymende7** [comment]
thanks
